### PR TITLE
fixes an error if encrypted_value is empty

### PR DESCRIPTION
**Pull request by nrllh**
It fixes the error *got an unexpected keyword argument encrypted_value - <class TypeError>*

### CODE REVIEW

**Comment by Arnie97** [comment]
The patch breaks support for any encrypted cookies.
Did you mean both `encrypted_value` and `value` were set to a valid value for the same row?
May you please report the Chrome version and operating system to produce this issue?

**Comment by Arnie97** [comment]
Okay, I got it. Both `encrypted_value` and `value` was empty, right?

**Comment by Arnie97** [comment]
I suppose that we should keep the cookie and send its key to the server, even if its value is empty, i.e. `Set-Cookie: someKey=;`
I've submitted a patch in 1fe7923b301b4f549d815503eb17308f0bb5ca32. Does it fix your problem?

**Comment by nrllh** [comment]
Thanks :)

**Pull request closed without merging**
